apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "spillway.fullname" . }}
  labels:
    {{- include "spillway.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["secrets", "configmaps"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: [""]
    resources: ["namespaces"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["secrets/finalizers", "configmaps/finalizers"]
    verbs: ["update"]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["create", "patch"]
  - apiGroups: ["coordination.k8s.io"]
    resources: ["leases"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["spillway.kroy.io"]
    resources: ["spillwayprofiles"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["spillway.kroy.io"]
    resources: ["spillwayprofiles/status"]
    verbs: ["get", "update", "patch"]
  - apiGroups: ["spillway.kroy.io"]
    resources: ["spillwayprofiles/finalizers"]
    verbs: ["update"]
